### ISSUE TITLE
Retrieved data is always the same after to the first request is sent to the server

### ISSUE THREAD

**Issue by mpvillafranca** [koalazak/geolang-express#2]
Hi, I was trying to include your i18n modules in a KeystoneJS blog I'm developing. When I start the server, it detects the user IP and set all the req.app.locals variables according to that. The problem is that, for the next request, all that data is still stored so it enters this condition:

````
if('countryLangData' in req.app.locals){
    //geo data already exist. skip
}
````

Let me know if I'm wrong, but I think that to make it session based, you need to use the `req.session` variable to store that data, instead of `req.app.locals`...

**Comment by koalazak** [comment]
The module use `req.app.locals` to expose useful geodata variables in views. This is done in each request. But also set `req.session[cookieLangName]=req.app.locals.countryLang;` in the first request.
